### ISSUE TITLE
License Only

### ISSUE THREAD

**Issue by ChrisKahrs** [NealAnalyticsLLC/bonsai_simpy_demo#1]
I see the license file, but not the rest.  Looking forward to it.  Thanks all!

**Comment by JoeLanska-NealAnalytics** [comment]
Hi @ChrisKahrs, I just added the initial release, which includes:
- the SimPy hospital simulation,
- the Bonsai simulation interface, and
- various configuration and deployment files.

Comments and suggestions are welcome.

Cheers :)
